In [1]:
!pip install ultralytics

Collecting ultralytics
  Downloading ultralytics-8.3.161-py3-none-any.whl.metadata (37 kB)
Requirement already satisfied: numpy>=1.23.0 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (1.26.4)
Requirement already satisfied: matplotlib>=3.3.0 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (3.7.2)
Requirement already satisfied: opencv-python>=4.6.0 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (4.11.0.86)
Requirement already satisfied: pillow>=7.1.2 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (11.1.0)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (6.0.2)
Requirement already satisfied: requests>=2.23.0 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (2.32.3)
Requirement already satisfied: scipy>=1.4.1 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (1.15.2)
Requirement already satisfied: torch>=1.8.0 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (2.6.0+cu124)
Requirement already satisfied: torchvision>=0.9.0 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (0.21.0+cu124)
Requirement already satisfied: tqdm>=4.64.0 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (4.67.1)
Requirement already satisfied: psutil in /usr/local/lib/python3.11/dist-packages (from ultralytics) (7.0.0)
Requirement already satisfied: py-cpuinfo in /usr/local/lib/python3.11/dist-packages (from ultralytics) (9.0.0)
Requirement already satisfied: pandas>=1.1.4 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (2.2.3)
Collecting ultralytics-thop>=2.0.0 (from ultralytics)
  Downloading ultralytics_thop-2.0.14-py3-none-any.whl.metadata (9.4 kB)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.3.0->ultralytics) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.3.0->ultralytics) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.3.0->ultralytics) (4.57.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.3.0->ultralytics) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.3.0->ultralytics) (25.0)
Requirement already satisfied: pyparsing<3.1,>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.3.0->ultralytics) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.3.0->ultralytics) (2.9.0.post0)
Requirement already satisfied: mkl_fft in /usr/local/lib/python3.11/dist-packages (from numpy>=1.23.0->ultralytics) (1.3.8)
Requirement already satisfied: mkl_random in /usr/local/lib/python3.11/dist-packages (from numpy>=1.23.0->ultralytics) (1.2.4)
Requirement already satisfied: mkl_umath in /usr/local/lib/python3.11/dist-packages (from numpy>=1.23.0->ultralytics) (0.1.1)
Requirement already satisfied: mkl in /usr/local/lib/python3.11/dist-packages (from numpy>=1.23.0->ultralytics) (2025.1.0)
Requirement already satisfied: tbb4py in /usr/local/lib/python3.11/dist-packages (from numpy>=1.23.0->ultralytics) (2022.1.0)
Requirement already satisfied: mkl-service in /usr/local/lib/python3.11/dist-packages (from numpy>=1.23.0->ultralytics) (2.4.1)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.1.4->ultralytics) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.1.4->ultralytics) (2025.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.23.0->ultralytics) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.23.0->ultralytics) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.23.0->ultralytics) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.23.0->ultralytics) (2025.4.26)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (3.18.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (4.13.2)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (2025.3.2)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (12.4.127)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (12.4.127)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (12.4.127)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (12.4.127)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch>=1.8.0->ultralytics) (1.3.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.7->matplotlib>=3.3.0->ultralytics) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch>=1.8.0->ultralytics) (3.0.2)
Requirement already satisfied: intel-openmp<2026,>=2024 in /usr/local/lib/python3.11/dist-packages (from mkl->numpy>=1.23.0->ultralytics) (2024.2.0)
Requirement already satisfied: tbb==2022.* in /usr/local/lib/python3.11/dist-packages (from mkl->numpy>=1.23.0->ultralytics) (2022.1.0)
Requirement already satisfied: tcmlib==1.* in /usr/local/lib/python3.11/dist-packages (from tbb==2022.*->mkl->numpy>=1.23.0->ultralytics) (1.3.0)
Requirement already satisfied: intel-cmplr-lib-rt in /usr/local/lib/python3.11/dist-packages (from mkl_umath->numpy>=1.23.0->ultralytics) (2024.2.0)
Requirement already satisfied: intel-cmplr-lib-ur==2024.2.0 in /usr/local/lib/python3.11/dist-packages (from intel-openmp<2026,>=2024->mkl->numpy>=1.23.0->ultralytics) (2024.2.0)
Downloading ultralytics-8.3.161-py3-none-any.whl (1.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 19.9 MB/s eta 0:00:00a 0:00:01
Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 4.6 MB/s eta 0:00:000:00:0100:01
Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.6 MB/s eta 0:00:000:00:0100:01
Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 7.9 MB/s eta 0:00:000:00:0100:01
Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 30.5 MB/s eta 0:00:00:00:0100:01
Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 9.6 MB/s eta 0:00:000:00:0100:01
Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 8.1 MB/s eta 0:00:000:00:0100:01
Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 63.1 MB/s eta 0:00:00:00:0100:01
Downloading ultralytics_thop-2.0.14-py3-none-any.whl (26 kB)
Installing collected packages: nvidia-nvjitlink-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cublas-cu12, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12, ultralytics-thop, ultralytics
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.9.41
    Uninstalling nvidia-nvjitlink-cu12-12.9.41:
      Successfully uninstalled nvidia-nvjitlink-cu12-12.9.41
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.10.19
    Uninstalling nvidia-curand-cu12-10.3.10.19:
      Successfully uninstalled nvidia-curand-cu12-10.3.10.19
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.4.0.6
    Uninstalling nvidia-cufft-cu12-11.4.0.6:
      Successfully uninstalled nvidia-cufft-cu12-11.4.0.6
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.9.0.13
    Uninstalling nvidia-cublas-cu12-12.9.0.13:
      Successfully uninstalled nvidia-cublas-cu12-12.9.0.13
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.9.5
    Uninstalling nvidia-cusparse-cu12-12.5.9.5:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.9.5
  Attempting uninstall: nvidia-cudnn-cu12
    Found existing installation: nvidia-cudnn-cu12 9.3.0.75
    Uninstalling nvidia-cudnn-cu12-9.3.0.75:
      Successfully uninstalled nvidia-cudnn-cu12-9.3.0.75
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.7.4.40
    Uninstalling nvidia-cusolver-cu12-11.7.4.40:
      Successfully uninstalled nvidia-cusolver-cu12-11.7.4.40
Successfully installed nvidia-cublas-cu12-12.4.5.8 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-nvjitlink-cu12-12.4.127 ultralytics-8.3.161 ultralytics-thop-2.0.14

In [2]:
import pandas as pd
import os
import numpy as np
import shutil
import yaml
import matplotlib.pyplot as plt
import random
import cv2

from sklearn import model_selection
from tqdm import tqdm
from glob import glob

In [3]:
size = 512
TRAIN_LABELS_PATH = './vinbigdata/labels/train'
VAL_LABELS_PATH = './vinbigdata/labels/val'
TRAIN_IMAGES_PATH = './vinbigdata/images/train' #12000
VAL_IMAGES_PATH = './vinbigdata/images/val' #3000
External_DIR = f'../input/vinbigdata-{size}-image-dataset/vinbigdata/train' # 15000
os.makedirs(TRAIN_LABELS_PATH, exist_ok = True)
os.makedirs(VAL_LABELS_PATH, exist_ok = True)
os.makedirs(TRAIN_IMAGES_PATH, exist_ok = True)
os.makedirs(VAL_IMAGES_PATH, exist_ok = True)

In [4]:
original_df = pd.read_csv('../input/vinbigdata-chest-xray-abnormalities-detection/train.csv')
number_of_imageids = len(original_df['image_id'].values)
print(f'Total number of image_ids (train + validation) {number_of_imageids}')

number_of_images = len(os.listdir('../input/vinbigdata-chest-xray-abnormalities-detection/train'))
print(f'Total number of images (train + validation) {number_of_images}')

number_of_labels = len(os.listdir('../input/vinbigdata-yolo-labels-dataset/labels'))
print(f'Total number of labels (train + validation) {number_of_labels}')

Total number of image_ids (train + validation) 67914
Total number of images (train + validation) 15000
Total number of labels (train + validation) 15000

In [5]:
import os
import cv2
import numpy as np
import pydicom
import multiprocessing
from tqdm import tqdm
from skimage import exposure

def dicom2array(path, voi_lut=True, fix_monochrome=True):
    dicom = pydicom.read_file(path)
    if voi_lut:
        data = apply_voi_lut(dicom.pixel_array, dicom)
    else:
        data = dicom.pixel_array
    if fix_monochrome and dicom.PhotometricInterpretation == "MONOCHROME1":
        data = np.amax(data) - data
    data = data - np.min(data)
    data = data / np.max(data)
    data = (data * 255).astype(np.uint8)
    return data

def process_image(dicom_path_output_dir):
    dicom_path, output_dir = dicom_path_output_dir
    file_name = os.path.splitext(os.path.basename(dicom_path))[0]
    image_array = dicom2array(dicom_path)
    equalized_image = exposure.equalize_hist(image_array)
    equalized_image = (equalized_image * 255).astype(np.uint8)
    cv2.imwrite(os.path.join(output_dir, f"{file_name}.jpeg"), equalized_image)

def saving_image(output_dir, dicom_path_list):
    os.makedirs(output_dir, exist_ok=True)
    dicom_path_output_dir_list = [(path, output_dir) for path in dicom_path_list]

    # Use multiprocessing Pool for parallel processing
    with multiprocessing.Pool() as pool:
        list(tqdm(pool.imap(process_image, dicom_path_output_dir_list), total=len(dicom_path_list), desc="Processing Images"))

In [6]:
df = pd.read_csv('/kaggle/input/vinbigdata-chest-xray-abnormalities-detection/train.csv')
number_of_images = len(df['image_id'].values)
print(f'Total number of image ids (train + validation) {number_of_images}')

df = df[df.class_id!=14].reset_index(drop = True)
number_of_images = len(df['image_id'].values)
print(f'Total number of image ids after dropping normal images (train + validation) {number_of_images}')

df.head()

Total number of image ids (train + validation) 67914
Total number of image ids after dropping normal images (train + validation) 36096

,image_id,class_name,class_id,rad_id,x_min,y_min,x_max,y_max
0,9a5094b2563a1ef3ff50dc5c7ff71345,Cardiomegaly,3,R10,691.0,1375.0,1653.0,1831.0
1,051132a778e61a86eb147c7c6f564dfe,Aortic enlargement,0,R10,1264.0,743.0,1611.0,1019.0
2,1c32170b4af4ce1a3030eb8167753b06,Pleural thickening,11,R9,627.0,357.0,947.0,433.0
3,0c7a38f293d5f5e4846aa4ca6db4daf1,ILD,5,R17,1347.0,245.0,2188.0,2169.0
4,47ed17dcb2cbeec15182ed335a8b5a9e,Nodule/Mass,8,R9,557.0,2352.0,675.0,2484.0

In [7]:
df = df.drop(columns=['class_name', 'rad_id', 'x_min', 'x_max', 'y_min', 'y_max',  'class_id']) # we only need image ids, labels are pre-made
df.head()

                           image_id
0  9a5094b2563a1ef3ff50dc5c7ff71345
1  051132a778e61a86eb147c7c6f564dfe
2  1c32170b4af4ce1a3030eb8167753b06
3  0c7a38f293d5f5e4846aa4ca6db4daf1
4  47ed17dcb2cbeec15182ed335a8b5a9e

In [8]:
df_train, df_valid = model_selection.train_test_split(df, test_size=0.05, random_state=42, shuffle=True)

In [9]:
number_of_images = len(df_train['image_id'].values)
print(f'Total number of training image_ids {number_of_images}')

number_of_images = len(df_valid['image_id'].values)
print(f'Total number of validation image_ids {number_of_images}')

Total number of training image_ids 34291
Total number of validation image_ids 1805

In [10]:
# need to delete duplicate image ids, len(labels) should be equal len(df.imageids.values),

In [11]:
print(f'Total number of training images {len(df_train.image_id.unique())}')
print(f'Total number of validation images {len(df_valid.image_id.unique())}')

Total number of training images 4394
Total number of validation images 1434

In [12]:
def preproccess_data(df, labels_path, images_path):
    for img_id in tqdm(df.image_id.unique()):
        shutil.copy(os.path.join('../input/vinbigdata-yolo-labels-dataset/labels', f"{img_id}"+'.txt'), labels_path)
        shutil.copy(os.path.join(f'/kaggle/input/vinbigdata-{size}-image-dataset/vinbigdata/train', f"{img_id}.png"), images_path)

In [13]:
preproccess_data(df_train, TRAIN_LABELS_PATH, TRAIN_IMAGES_PATH)
preproccess_data(df_valid, VAL_LABELS_PATH, VAL_IMAGES_PATH)

100%|██████████| 4394/4394 [01:08<00:00, 63.96it/s]
100%|██████████| 1434/1434 [00:03<00:00, 419.16it/s]

In [14]:
# check that data was preprocessed correctly
print(len(os.listdir(TRAIN_LABELS_PATH)))
print(len(os.listdir(TRAIN_IMAGES_PATH)))

print(len(os.listdir(VAL_LABELS_PATH)))
print(len(os.listdir(VAL_IMAGES_PATH)))

4394
4394
1434
1434

In [15]:
# credit / source https://www.kaggle.com/awsaf49/vinbigdata-cxr-ad-yolov5-14-class-train
classes = [ 'Aortic enlargement',
            'Atelectasis',
            'Calcification',
            'Cardiomegaly',
            'Consolidation',
            'ILD',
            'Infiltration',
            'Lung Opacity',
            'Nodule/Mass',
            'Other lesion',
            'Pleural effusion',
            'Pleural thickening',
            'Pneumothorax',
            'Pulmonary fibrosis']

data = dict(
    train =  '../vinbigdata/images/train',
    val   =  '../vinbigdata/images/val',
    nc    = 14,
    names = classes
    )

with open('/kaggle/working/vinbigdata.yaml', 'w') as outfile:
    yaml.dump(data, outfile, default_flow_style=False)

f = open(os.path.join( os.getcwd() , 'vinbigdata.yaml'), 'r')
print('\nyaml:')
print(f.read())

yaml:
names:
- Aortic enlargement
- Atelectasis
- Calcification
- Cardiomegaly
- Consolidation
- ILD
- Infiltration
- Lung Opacity
- Nodule/Mass
- Other lesion
- Pleural effusion
- Pleural thickening
- Pneumothorax
- Pulmonary fibrosis
nc: 14
train: ../vinbigdata/images/train
val: ../vinbigdata/images/val

In [16]:
import os
from ultralytics import YOLO
import torch

# Environment setup
os.environ["WANDB_MODE"] = "dryrun"
os.environ["CUDA_VISIBLE_DEVICES"] = "0,1"  # Make both GPUs visible

def setup_finetuning():
    # Verify CUDA availability
    if not torch.cuda.is_available():
        raise RuntimeError("CUDA is not available. Check your GPU configuration.")
    
    print(f"⚡ Available GPUs: {torch.cuda.device_count()}")
    assert torch.cuda.device_count() >= 2, "Need at least 2 GPUs for this configuration"
    
    # Load YOUR custom pretrained model
    model_path = '/kaggle/input/modfee/yolo12s 77map.pt'
    model = YOLO(model_path)
    print(f"\n🔧 Loaded custom model from: {model_path}")
    
    # Find dataset (modify as needed)
    dataset_path = './vinbigdata.yaml'
    if not os.path.exists(dataset_path):
        print("\n🔍 Searching for dataset...")
        !find /kaggle/input -name "data.yaml"  # Search entire input directory
        for root, _, files in os.walk('/kaggle/input'):
            if 'data.yaml' in files:
                dataset_path = os.path.join(root, 'data.yaml')
                break
        else:
            raise FileNotFoundError("data.yaml not found in /kaggle/input")
    print(f"✅ Found dataset at: {dataset_path}")

    # Fine-tuning configuration
    train_args = {
        'data': dataset_path,
        'epochs': 200,  # Typically fewer epochs for fine-tuning
        'batch': 32,   # 16 per GPU
        'device': [0, 1],
        'workers': 8,  # 4 per GPU
        
        # Fine-tuning specific settings
        'optimizer': 'AdamW',  # Better for fine-tuning
        'lr0': 0.0001,  # Lower learning rate than pretraining
        'lrf': 0.01,    # Final LR = 0.000001
        'cos_lr': True,  # Smooth LR decay
        'warmup_epochs': 3,
        
        # Augmentations (moderate)
        'imgsz': 640,
        'mosaic': 0.3,  # Less aggressive than pretraining
        'fliplr': 0.3,
        
        # Performance
        'amp': True,
        'cache': 'ram',
        'resume': False,  # Important for fine-tuning
        'pretrained': False,  # Use our custom weights
        'name': 'mbvfss_finetune'
    }
    
    return model, train_args

def main():
    try:
        # Verify environment
        print("\n🔍 Hardware verification:")
        !nvidia-smi --query-gpu=name,memory.total --format=csv
        
        model, train_args = setup_finetuning()
        
        # Pre-training validation
        print("\n🔍 Running initial validation...")
        model.val(
            data=train_args['data'],
            batch=32,
            device=[0,1],
            workers=8
        )
        
        # Start fine-tuning
        print(f"\n🚀 Fine-tuning with batch={train_args['batch']} (16 per GPU)")
        model.train(**train_args)
        
        # Final validation
        print("\n🎯 Final validation:")
        model.val(
            data=train_args['data'],
            batch=32,
            device=[0,1],
            plots=True
        )
        
    except Exception as e:
        print(f"\n❌ Error: {str(e)}")
        print("\n💡 Debugging tips:")
        print("1. Verify model path exists: !ls /kaggle/input/mbvfss")
        print("2. Check dataset structure: !cat {train_args['data']}")
        print("3. Try reducing batch size if OOM occurs")

if __name__ == "__main__":
    main()

Creating new Ultralytics Settings v0.0.6 file ✅
View Ultralytics Settings with 'yolo settings' or at '/root/.config/Ultralytics/settings.json'
Update Settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/quickstart/#ultralytics-settings.

🔍 Hardware verification:
name, memory.total [MiB]
Tesla T4, 15360 MiB
Tesla T4, 15360 MiB
⚡ Available GPUs: 2

🔧 Loaded custom model from: /kaggle/input/modfee/yolo12s 77map.pt
✅ Found dataset at: ./vinbigdata.yaml

🔍 Running initial validation...
Ultralytics 8.3.161 🚀 Python-3.11.11 torch-2.6.0+cu124 CUDA:0 (Tesla T4, 15095MiB)
                                                        CUDA:1 (Tesla T4, 15095MiB)
YOLOv12s summary (fused): 159 layers, 9,236,298 parameters, 0 gradients, 21.2 GFLOPs
Downloading https://ultralytics.com/assets/Arial.ttf to '/root/.config/Ultralytics/Arial.ttf'...

100%|██████████| 755k/755k [00:00<00:00, 18.8MB/s]

val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 2403.8±669.0 MB/s, size: 135.0 KB)

val: Scanning /kaggle/working/vinbigdata/labels/val... 1434 images, 0 backgrounds, 0 corrupt: 100%|██████████| 1434/1434 [00:02<00:00, 679.63it/s]

val: New cache created: /kaggle/working/vinbigdata/labels/val.cache

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:26<00:00,  1.70it/s]
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all       1434      14888      0.903      0.678      0.778      0.623
    Aortic enlargement       1000       2282      0.965      0.592      0.754      0.628
           Atelectasis         85        128      0.886      0.781      0.865       0.72
         Calcification        192        443      0.809      0.589      0.713      0.495
          Cardiomegaly        745       1725      0.982      0.569      0.734      0.641
         Consolidation        170        288      0.909      0.785      0.843      0.721
                   ILD        161        419      0.956      0.771      0.845      0.753
          Infiltration        263        564      0.912      0.751      0.833      0.704
          Lung Opacity        559       1210      0.911      0.726      0.834      0.678
           Nodule/Mass        344       1368        0.8       0.52      0.613      0.423
          Other lesion        445        989      0.898       0.75      0.841      0.655
      Pleural effusion        460       1155      0.892      0.656      0.782      0.577
    Pleural thickening        782       2165      0.857       0.71      0.809      0.557
          Pneumothorax         38         87          1      0.628      0.659      0.593
    Pulmonary fibrosis        657       2065      0.866      0.667      0.768      0.575
Speed: 0.6ms preprocess, 13.2ms inference, 0.0ms loss, 0.9ms postprocess per image
Results saved to runs/detect/val

🚀 Fine-tuning with batch=32 (16 per GPU)
Ultralytics 8.3.161 🚀 Python-3.11.11 torch-2.6.0+cu124 CUDA:0 (Tesla T4, 15095MiB)
                                                        CUDA:1 (Tesla T4, 15095MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=ram, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=True, cutmix=0.0, data=./vinbigdata.yaml, degrees=0.0, deterministic=True, device=0,1, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=200, erasing=0.4, exist_ok=False, fliplr=0.3, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.0001, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=/kaggle/input/modfee/yolo12s 77map.pt, momentum=0.937, mosaic=0.3, multi_scale=False, name=mbvfss_finetune, nbs=64, nms=False, opset=None, optimize=False, optimizer=AdamW, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=False, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=runs/detect/mbvfss_finetune, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  3                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  4                  -1  1    103360  ultralytics.nn.modules.block.C3k2            [128, 256, 1, False, 0.25]
  5                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
  6                  -1  2    689408  ultralytics.nn.modules.block.A2C2f           [256, 256, 2, True, 4]
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
  8                  -1  2   2689536  ultralytics.nn.modules.block.A2C2f           [512, 512, 2, True, 1]
  9                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 10             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 11                  -1  1    345856  ultralytics.nn.modules.block.A2C2f           [768, 256, 1, False, -1]
 12                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 13             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 14                  -1  1     95104  ultralytics.nn.modules.block.A2C2f           [512, 128, 1, False, -1]
 15                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 16            [-1, 11]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 17                  -1  1    296704  ultralytics.nn.modules.block.A2C2f           [384, 256, 1, False, -1]
 18                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 19             [-1, 8]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 20                  -1  1   1511424  ultralytics.nn.modules.block.C3k2            [768, 512, 1, True]
 21        [14, 17, 20]  1    824826  ultralytics.nn.modules.head.Detect           [14, [128, 256, 512]]
YOLOv12s summary: 272 layers, 9,258,554 parameters, 9,258,538 gradients, 21.6 GFLOPs

Transferred 126/691 items from pretrained weights
DDP: debug command /usr/bin/python3 -m torch.distributed.run --nproc_per_node 2 --master_port 35207 /root/.config/Ultralytics/DDP/_temp_vhg7j889140605829568656.py
Ultralytics 8.3.161 🚀 Python-3.11.11 torch-2.6.0+cu124 CUDA:0 (Tesla T4, 15095MiB)
                                                        CUDA:1 (Tesla T4, 15095MiB)
Transferred 691/691 items from pretrained weights
Freezing layer 'model.21.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
Downloading https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11n.pt to 'yolo11n.pt'...

100%|██████████| 5.35M/5.35M [00:00<00:00, 77.0MB/s]

AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 1870.9±389.8 MB/s, size: 134.4 KB)

train: Scanning /kaggle/working/vinbigdata/labels/train... 4394 images, 0 backgrounds, 0 corrupt: 100%|██████████| 4394/4394 [00:06<00:00, 655.07it/s]

train: New cache created: /kaggle/working/vinbigdata/labels/train.cache
WARNING ⚠️ cache='ram' may produce non-deterministic training results. Consider cache='disk' as a deterministic alternative if your disk space allows.

train: Caching images (5.0GB RAM): 100%|██████████| 4394/4394 [00:09<00:00, 477.03it/s]

albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, num_output_channels=3, method='weighted_average'), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 980.2±703.8 MB/s, size: 135.3 KB)

val: Scanning /kaggle/working/vinbigdata/labels/val.cache... 1434 images, 0 backgrounds, 0 corrupt: 100%|██████████| 1434/1434 [00:00<?, ?it/s]

WARNING ⚠️ cache='ram' may produce non-deterministic training results. Consider cache='disk' as a deterministic alternative if your disk space allows.

val: Caching images (1.6GB RAM): 100%|██████████| 1434/1434 [00:05<00:00, 248.75it/s]

Plotting labels to runs/detect/mbvfss_finetune/labels.jpg...
optimizer: AdamW(lr=0.0001, momentum=0.937) with parameter groups 113 weight(decay=0.0), 120 weight(decay=0.0005), 119 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to runs/detect/mbvfss_finetune
Starting training for 200 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      1/200      6.03G      1.136     0.9482      1.229         28        640: 100%|██████████| 138/138 [01:10<00:00,  1.97it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:18<00:00,  2.45it/s]

                   all       1434      14888      0.531      0.398      0.406      0.227

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      2/200      6.82G      1.097     0.8947        1.2         37        640: 100%|██████████| 138/138 [01:11<00:00,  1.94it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:18<00:00,  2.43it/s]

                   all       1434      14888      0.812      0.625      0.726      0.522

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      3/200      6.86G      1.039     0.8358      1.176         45        640: 100%|██████████| 138/138 [01:10<00:00,  1.97it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:18<00:00,  2.42it/s]

                   all       1434      14888      0.877      0.659      0.764       0.58

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      4/200       6.9G      1.045     0.8375       1.18         21        640: 100%|██████████| 138/138 [01:10<00:00,  1.96it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:18<00:00,  2.42it/s]

                   all       1434      14888      0.872      0.668      0.768      0.585

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      5/200       6.9G      1.043     0.8338      1.171         52        640: 100%|██████████| 138/138 [01:11<00:00,  1.94it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:18<00:00,  2.39it/s]

                   all       1434      14888      0.886      0.658      0.762      0.582

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      6/200       6.9G      1.043     0.8323      1.172         70        640: 100%|██████████| 138/138 [01:12<00:00,  1.91it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:18<00:00,  2.40it/s]

                   all       1434      14888      0.886      0.654      0.763       0.58

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      7/200       6.9G       1.03     0.8241      1.166         32        640: 100%|██████████| 138/138 [01:12<00:00,  1.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:18<00:00,  2.42it/s]

                   all       1434      14888      0.871      0.655      0.759      0.575

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      8/200       6.9G      1.027     0.8264      1.165         76        640: 100%|██████████| 138/138 [01:12<00:00,  1.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:18<00:00,  2.41it/s]

                   all       1434      14888      0.888      0.658      0.766      0.582

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      9/200       6.9G      1.044     0.8361      1.179         54        640: 100%|██████████| 138/138 [01:12<00:00,  1.91it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:18<00:00,  2.43it/s]

                   all       1434      14888      0.865      0.667      0.761       0.58

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     10/200       6.9G      1.041     0.8292      1.176         43        640: 100%|██████████| 138/138 [01:12<00:00,  1.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:18<00:00,  2.43it/s]

                   all       1434      14888      0.875      0.657      0.765      0.578

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     11/200       6.9G      1.044      0.834       1.17         46        640: 100%|██████████| 138/138 [01:12<00:00,  1.91it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:18<00:00,  2.43it/s]

                   all       1434      14888       0.88      0.663      0.764      0.582

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     12/200       6.9G      1.036     0.8227      1.167         45        640: 100%|██████████| 138/138 [01:12<00:00,  1.91it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:18<00:00,  2.44it/s]

                   all       1434      14888      0.871      0.658      0.758      0.576

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     13/200       6.9G       1.03     0.8144      1.164         41        640: 100%|██████████| 138/138 [01:11<00:00,  1.92it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:18<00:00,  2.44it/s]

                   all       1434      14888      0.883      0.667      0.766      0.586

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     14/200      6.91G      1.034     0.8238      1.165         47        640: 100%|██████████| 138/138 [01:11<00:00,  1.93it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:18<00:00,  2.41it/s]

                   all       1434      14888      0.885      0.666      0.769      0.586

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     15/200      6.91G      1.017     0.8151      1.162         41        640: 100%|██████████| 138/138 [01:11<00:00,  1.93it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:18<00:00,  2.45it/s]

                   all       1434      14888      0.884      0.661      0.764      0.585

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     16/200      6.91G      1.026     0.8136      1.167         44        640: 100%|██████████| 138/138 [01:11<00:00,  1.92it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:18<00:00,  2.43it/s]

                   all       1434      14888      0.884       0.66      0.764      0.584

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     17/200      6.91G      1.045     0.8337      1.171         79        640: 100%|██████████| 138/138 [01:12<00:00,  1.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:18<00:00,  2.38it/s]

                   all       1434      14888      0.884      0.665      0.767      0.586

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     18/200      6.91G      1.037     0.8263       1.17         56        640: 100%|██████████| 138/138 [01:12<00:00,  1.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:18<00:00,  2.43it/s]

                   all       1434      14888      0.881      0.666      0.768      0.586

  0%|          | 0/138 [00:00<?, ?it/s]

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     19/200      6.91G      1.036     0.8195      1.155         40        640: 100%|██████████| 138/138 [01:12<00:00,  1.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:18<00:00,  2.37it/s]

                   all       1434      14888      0.878      0.671      0.768      0.586

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     20/200      6.91G      1.016     0.8139      1.156         40        640: 100%|██████████| 138/138 [01:13<00:00,  1.88it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:18<00:00,  2.38it/s]

                   all       1434      14888        0.9      0.662      0.769      0.587

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     21/200      6.91G       1.02     0.8101      1.158         57        640: 100%|██████████| 138/138 [01:12<00:00,  1.89it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:18<00:00,  2.42it/s]

                   all       1434      14888      0.889      0.666      0.769      0.591

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     22/200      6.91G      1.031     0.8199      1.168         70        640: 100%|██████████| 138/138 [01:12<00:00,  1.89it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:18<00:00,  2.38it/s]

                   all       1434      14888      0.889      0.664      0.769      0.588

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     23/200      6.91G      1.015     0.8161      1.157         43        640: 100%|██████████| 138/138 [01:13<00:00,  1.88it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:18<00:00,  2.39it/s]

                   all       1434      14888      0.892      0.663       0.77      0.592

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     24/200      6.91G      1.022     0.8086      1.162         30        640: 100%|██████████| 138/138 [01:13<00:00,  1.88it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:18<00:00,  2.37it/s]

                   all       1434      14888      0.891      0.668      0.769      0.591

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     25/200      6.91G      1.012     0.7972      1.162         31        640: 100%|██████████| 138/138 [01:12<00:00,  1.89it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:18<00:00,  2.37it/s]

                   all       1434      14888      0.889      0.668      0.769       0.59

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     26/200      6.91G      1.025     0.8135      1.162         25        640: 100%|██████████| 138/138 [01:13<00:00,  1.88it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.36it/s]

                   all       1434      14888      0.893      0.665       0.77      0.592

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     27/200      6.91G      1.013     0.8056      1.152         38        640: 100%|██████████| 138/138 [01:12<00:00,  1.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:18<00:00,  2.37it/s]

                   all       1434      14888      0.891      0.665      0.771      0.594

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     28/200      6.91G      1.017     0.8051      1.153         29        640: 100%|██████████| 138/138 [01:12<00:00,  1.91it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:18<00:00,  2.41it/s]

                   all       1434      14888      0.898      0.664      0.769      0.593

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     29/200      6.91G      1.017     0.8019      1.159         62        640: 100%|██████████| 138/138 [01:11<00:00,  1.93it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:18<00:00,  2.42it/s]

                   all       1434      14888      0.904       0.66      0.774      0.594

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     30/200      6.91G      1.017      0.798      1.154         50        640: 100%|██████████| 138/138 [01:11<00:00,  1.94it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:18<00:00,  2.40it/s]

                   all       1434      14888      0.892      0.666       0.77      0.594

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     31/200      6.91G      1.021     0.8032      1.154         84        640: 100%|██████████| 138/138 [01:10<00:00,  1.94it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:18<00:00,  2.39it/s]

                   all       1434      14888       0.89      0.664       0.77      0.593

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     32/200      6.91G      1.015     0.7958      1.153         65        640: 100%|██████████| 138/138 [01:11<00:00,  1.94it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:18<00:00,  2.41it/s]

                   all       1434      14888      0.893      0.674      0.771      0.595

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     33/200      6.91G      1.006     0.7891      1.158         57        640: 100%|██████████| 138/138 [01:11<00:00,  1.94it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:18<00:00,  2.37it/s]

                   all       1434      14888      0.892      0.672      0.773      0.598

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     34/200      6.91G      1.007     0.7986      1.155         39        640: 100%|██████████| 138/138 [01:11<00:00,  1.92it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.36it/s]

                   all       1434      14888      0.894      0.674      0.773      0.597

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     35/200      6.91G      1.013     0.7996      1.152         27        640: 100%|██████████| 138/138 [01:12<00:00,  1.91it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:18<00:00,  2.39it/s]

                   all       1434      14888      0.889      0.673      0.773      0.597

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     36/200      6.91G       1.01     0.7998      1.156         27        640: 100%|██████████| 138/138 [01:12<00:00,  1.89it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:18<00:00,  2.43it/s]

                   all       1434      14888      0.892       0.67      0.772      0.598

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     37/200      6.91G     0.9974     0.7842      1.154         61        640: 100%|██████████| 138/138 [01:12<00:00,  1.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:18<00:00,  2.43it/s]

                   all       1434      14888      0.899      0.669      0.774        0.6

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     38/200      6.91G     0.9995     0.7835      1.153         29        640: 100%|██████████| 138/138 [01:12<00:00,  1.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:18<00:00,  2.42it/s]

                   all       1434      14888      0.893      0.677      0.776      0.603

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     39/200      6.91G     0.9975     0.7918      1.147         46        640: 100%|██████████| 138/138 [01:12<00:00,  1.91it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:18<00:00,  2.44it/s]

                   all       1434      14888      0.896      0.675      0.777      0.602

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     40/200      6.91G      0.988     0.7794      1.146         38        640: 100%|██████████| 138/138 [01:12<00:00,  1.91it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:18<00:00,  2.42it/s]

                   all       1434      14888      0.894      0.671      0.774      0.599

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     41/200      6.91G      1.001     0.7903      1.146         29        640: 100%|██████████| 138/138 [01:12<00:00,  1.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:18<00:00,  2.41it/s]

                   all       1434      14888      0.902      0.674      0.775      0.605

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     42/200      6.91G     0.9984     0.7851      1.142         45        640: 100%|██████████| 138/138 [01:12<00:00,  1.91it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:18<00:00,  2.40it/s]

                   all       1434      14888      0.894      0.678      0.776      0.601

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     43/200      6.91G      1.008     0.7883      1.139         43        640: 100%|██████████| 138/138 [01:12<00:00,  1.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:18<00:00,  2.39it/s]

                   all       1434      14888      0.894      0.677      0.777      0.604

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     44/200      6.91G     0.9916     0.7793      1.141         44        640: 100%|██████████| 138/138 [01:13<00:00,  1.88it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.34it/s]

                   all       1434      14888      0.895       0.68      0.776      0.603

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     45/200      6.91G     0.9959     0.7784       1.14         38        640: 100%|██████████| 138/138 [01:14<00:00,  1.86it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.36it/s]

                   all       1434      14888       0.89      0.681      0.778      0.605

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     46/200      6.91G     0.9906     0.7795      1.138         35        640: 100%|██████████| 138/138 [01:13<00:00,  1.87it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.34it/s]

                   all       1434      14888      0.902      0.673      0.778      0.606

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     47/200      6.91G     0.9913     0.7769      1.147         38        640: 100%|██████████| 138/138 [01:13<00:00,  1.87it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:18<00:00,  2.38it/s]

                   all       1434      14888      0.906      0.672      0.777      0.606

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     48/200      6.91G     0.9845     0.7726      1.133         58        640: 100%|██████████| 138/138 [01:13<00:00,  1.89it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:18<00:00,  2.38it/s]

                   all       1434      14888      0.905      0.682      0.778      0.608

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     49/200      6.91G     0.9933     0.7836      1.144         36        640: 100%|██████████| 138/138 [01:13<00:00,  1.88it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:18<00:00,  2.37it/s]

                   all       1434      14888      0.909      0.673      0.778      0.608

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     50/200      6.91G     0.9961     0.7711      1.142         46        640: 100%|██████████| 138/138 [01:13<00:00,  1.87it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.35it/s]

                   all       1434      14888      0.904      0.678      0.776      0.609

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     51/200      6.91G     0.9802     0.7832      1.143         31        640: 100%|██████████| 138/138 [01:13<00:00,  1.88it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.35it/s]

                   all       1434      14888      0.898      0.679      0.777      0.608

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     52/200      6.91G     0.9798     0.7701      1.136         54        640: 100%|██████████| 138/138 [01:13<00:00,  1.88it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.36it/s]

                   all       1434      14888       0.91      0.681      0.779       0.61

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     53/200      6.91G     0.9845     0.7688      1.138         49        640: 100%|██████████| 138/138 [01:13<00:00,  1.87it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.34it/s]

                   all       1434      14888      0.913      0.676      0.776      0.609

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     54/200      6.91G     0.9882     0.7735      1.138         45        640: 100%|██████████| 138/138 [01:14<00:00,  1.86it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:18<00:00,  2.37it/s]

                   all       1434      14888       0.91      0.676      0.779       0.61

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     55/200      6.91G     0.9717     0.7622      1.137         45        640: 100%|██████████| 138/138 [01:13<00:00,  1.88it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.37it/s]

                   all       1434      14888      0.899      0.681      0.779      0.612

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     56/200      6.91G     0.9861      0.759      1.135         37        640: 100%|██████████| 138/138 [01:13<00:00,  1.87it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:18<00:00,  2.37it/s]

                   all       1434      14888      0.901      0.687      0.782      0.614

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     57/200      6.91G     0.9752     0.7562      1.138         47        640: 100%|██████████| 138/138 [01:13<00:00,  1.87it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:18<00:00,  2.39it/s]

                   all       1434      14888      0.899      0.684      0.782      0.615

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     58/200      6.91G     0.9703     0.7563      1.128         37        640: 100%|██████████| 138/138 [01:13<00:00,  1.88it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:18<00:00,  2.38it/s]

                   all       1434      14888        0.9      0.682      0.782      0.618

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     59/200      6.91G     0.9745      0.767      1.131         30        640: 100%|██████████| 138/138 [01:14<00:00,  1.86it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:18<00:00,  2.37it/s]

                   all       1434      14888      0.902      0.683      0.783      0.618

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     60/200      6.91G     0.9715     0.7572      1.127         37        640: 100%|██████████| 138/138 [01:13<00:00,  1.87it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.35it/s]

                   all       1434      14888      0.911      0.674       0.78      0.614

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     61/200      6.91G     0.9616      0.745      1.126         66        640: 100%|██████████| 138/138 [01:13<00:00,  1.86it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.36it/s]

                   all       1434      14888      0.907      0.685      0.783      0.619

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     62/200      6.91G     0.9548     0.7446      1.115         35        640: 100%|██████████| 138/138 [01:14<00:00,  1.86it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.33it/s]

                   all       1434      14888      0.907      0.685      0.783      0.621

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     63/200      6.91G     0.9586     0.7492      1.125         26        640: 100%|██████████| 138/138 [01:13<00:00,  1.87it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.33it/s]

                   all       1434      14888      0.909      0.683      0.781      0.619

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     64/200      6.91G     0.9687       0.76      1.128         53        640: 100%|██████████| 138/138 [01:12<00:00,  1.89it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.32it/s]

                   all       1434      14888      0.909      0.678      0.782      0.618

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     65/200      6.91G     0.9614     0.7456      1.122         65        640: 100%|██████████| 138/138 [01:12<00:00,  1.89it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.34it/s]

                   all       1434      14888      0.908      0.686      0.785      0.623

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     66/200      6.91G     0.9611     0.7486      1.118         90        640: 100%|██████████| 138/138 [01:12<00:00,  1.89it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.33it/s]

                   all       1434      14888      0.901      0.688      0.783      0.622

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     67/200      6.91G     0.9585     0.7471      1.127         35        640: 100%|██████████| 138/138 [01:12<00:00,  1.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.34it/s]

                   all       1434      14888      0.908      0.683      0.783      0.622

  0%|          | 0/138 [00:00<?, ?it/s]

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     68/200      6.91G     0.9582     0.7418      1.118         42        640: 100%|██████████| 138/138 [01:12<00:00,  1.91it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.34it/s]

                   all       1434      14888      0.916      0.685      0.786      0.624

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     69/200      6.91G     0.9533     0.7362       1.12         43        640: 100%|██████████| 138/138 [01:12<00:00,  1.91it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.35it/s]

                   all       1434      14888      0.916      0.685      0.785      0.626

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     70/200      6.91G     0.9564     0.7449      1.121         51        640: 100%|██████████| 138/138 [01:12<00:00,  1.91it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.33it/s]

                   all       1434      14888      0.915      0.683      0.781      0.625

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     71/200      6.91G     0.9514      0.738      1.123         58        640: 100%|██████████| 138/138 [01:12<00:00,  1.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.33it/s]

                   all       1434      14888      0.905      0.687      0.786      0.627

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     72/200      6.91G     0.9478     0.7257      1.107         76        640: 100%|██████████| 138/138 [01:12<00:00,  1.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.34it/s]

                   all       1434      14888      0.919      0.685      0.785      0.629

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     73/200      6.91G     0.9552     0.7428      1.124         61        640: 100%|██████████| 138/138 [01:13<00:00,  1.88it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.31it/s]

                   all       1434      14888       0.92      0.684      0.785      0.629

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     74/200      6.91G     0.9352     0.7218       1.11         40        640: 100%|██████████| 138/138 [01:13<00:00,  1.89it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.30it/s]

                   all       1434      14888      0.916      0.685      0.784      0.629

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     75/200      6.91G     0.9367     0.7242      1.106         66        640: 100%|██████████| 138/138 [01:12<00:00,  1.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.32it/s]

                   all       1434      14888       0.91      0.689      0.785       0.63

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     76/200      6.91G     0.9497     0.7375      1.114         62        640: 100%|██████████| 138/138 [01:12<00:00,  1.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.31it/s]

                   all       1434      14888      0.909      0.693      0.786      0.632

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     77/200      6.91G     0.9446     0.7308      1.113         39        640: 100%|██████████| 138/138 [01:12<00:00,  1.91it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.32it/s]

                   all       1434      14888      0.921      0.687      0.785      0.632

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     78/200      6.91G     0.9469     0.7271       1.11         37        640: 100%|██████████| 138/138 [01:12<00:00,  1.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.31it/s]

                   all       1434      14888      0.913      0.687      0.786      0.632

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     79/200      6.91G     0.9446     0.7204      1.108         20        640: 100%|██████████| 138/138 [01:13<00:00,  1.88it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.31it/s]

                   all       1434      14888      0.919      0.692       0.79      0.635

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     80/200      6.91G      0.931     0.7257      1.113         30        640: 100%|██████████| 138/138 [01:12<00:00,  1.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.31it/s]

                   all       1434      14888      0.922      0.688      0.788      0.636

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     81/200      6.91G      0.928     0.7163      1.101         60        640: 100%|██████████| 138/138 [01:12<00:00,  1.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.32it/s]

                   all       1434      14888      0.922       0.69      0.791      0.636

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     82/200      6.91G     0.9348     0.7272      1.108         37        640: 100%|██████████| 138/138 [01:12<00:00,  1.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.31it/s]

                   all       1434      14888      0.927      0.685      0.789      0.636

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     83/200      6.91G     0.9255      0.711      1.102         56        640: 100%|██████████| 138/138 [01:12<00:00,  1.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.32it/s]

                   all       1434      14888      0.925      0.687      0.788      0.638

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     84/200      6.91G     0.9158     0.7114      1.097         58        640: 100%|██████████| 138/138 [01:13<00:00,  1.87it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.31it/s]

                   all       1434      14888      0.923      0.689      0.791      0.636

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     85/200      6.91G     0.9275     0.7095      1.102         45        640: 100%|██████████| 138/138 [01:13<00:00,  1.87it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.30it/s]

                   all       1434      14888      0.924       0.69      0.791      0.639

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     86/200      6.91G     0.9397     0.7158      1.103         26        640: 100%|██████████| 138/138 [01:12<00:00,  1.89it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.32it/s]

                   all       1434      14888      0.926      0.689      0.791       0.64

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     87/200      6.91G     0.9188     0.7073      1.098         41        640: 100%|██████████| 138/138 [01:12<00:00,  1.89it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.31it/s]

                   all       1434      14888      0.919      0.695      0.791      0.641

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     88/200      6.91G     0.9228     0.7138      1.097         29        640: 100%|██████████| 138/138 [01:13<00:00,  1.88it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.31it/s]

                   all       1434      14888      0.932      0.692       0.79       0.64

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     89/200      6.91G     0.9165     0.7072      1.096         44        640: 100%|██████████| 138/138 [01:12<00:00,  1.89it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.31it/s]

                   all       1434      14888      0.929      0.692      0.793      0.642

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     90/200      6.91G     0.9143     0.7055      1.096         65        640: 100%|██████████| 138/138 [01:12<00:00,  1.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.33it/s]

                   all       1434      14888      0.919      0.693       0.79      0.641

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     91/200      6.91G     0.9179      0.709        1.1         48        640: 100%|██████████| 138/138 [01:12<00:00,  1.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.30it/s]

                   all       1434      14888      0.932      0.686      0.792      0.643

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     92/200      6.91G     0.9205      0.708      1.103         40        640: 100%|██████████| 138/138 [01:12<00:00,  1.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.31it/s]

                   all       1434      14888      0.926      0.696      0.794      0.643

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     93/200      6.91G     0.9091     0.7028      1.095         34        640: 100%|██████████| 138/138 [01:12<00:00,  1.91it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.35it/s]

                   all       1434      14888      0.931      0.694      0.793      0.646

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     94/200      6.91G     0.9161     0.7066        1.1         46        640: 100%|██████████| 138/138 [01:12<00:00,  1.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.35it/s]

                   all       1434      14888       0.93      0.694       0.79      0.642

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     95/200      6.91G     0.9049     0.6933      1.088         40        640: 100%|██████████| 138/138 [01:13<00:00,  1.89it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.33it/s]

                   all       1434      14888      0.927      0.694      0.792      0.645

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     96/200      6.91G      0.904     0.6986      1.088         63        640: 100%|██████████| 138/138 [01:13<00:00,  1.87it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.31it/s]

                   all       1434      14888      0.916      0.699      0.793      0.644

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     97/200      6.91G     0.9087     0.7004      1.092         47        640: 100%|██████████| 138/138 [01:13<00:00,  1.87it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.33it/s]

                   all       1434      14888      0.927      0.691      0.793      0.647

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     98/200      6.91G     0.9143     0.7017      1.093         36        640: 100%|██████████| 138/138 [01:13<00:00,  1.87it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.31it/s]

                   all       1434      14888      0.925      0.693      0.792      0.647

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     99/200      6.91G     0.9017     0.6862      1.086         60        640: 100%|██████████| 138/138 [01:13<00:00,  1.88it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.31it/s]

                   all       1434      14888      0.936       0.69      0.794      0.649

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    100/200      6.91G     0.9066     0.6992      1.088         58        640: 100%|██████████| 138/138 [01:12<00:00,  1.89it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.33it/s]

                   all       1434      14888      0.933      0.689      0.792      0.648

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    101/200      6.91G     0.9049     0.7045      1.095         46        640: 100%|██████████| 138/138 [01:12<00:00,  1.91it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.32it/s]

                   all       1434      14888      0.928      0.691      0.793      0.648

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    102/200      6.91G     0.8972     0.6918      1.087         63        640: 100%|██████████| 138/138 [01:12<00:00,  1.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.31it/s]

                   all       1434      14888      0.929      0.693      0.793      0.649

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    103/200      6.91G      0.897     0.6948      1.091         32        640: 100%|██████████| 138/138 [01:12<00:00,  1.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.32it/s]

                   all       1434      14888      0.929      0.694      0.793      0.649

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    104/200      6.91G     0.8916       0.69      1.083         56        640: 100%|██████████| 138/138 [01:12<00:00,  1.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.31it/s]

                   all       1434      14888      0.933      0.695      0.793       0.65

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    105/200      6.91G     0.8808     0.6803      1.083         41        640: 100%|██████████| 138/138 [01:12<00:00,  1.91it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.35it/s]

                   all       1434      14888      0.944       0.69      0.793      0.652

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    106/200      6.91G     0.8989      0.689      1.086         28        640: 100%|██████████| 138/138 [01:12<00:00,  1.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.35it/s]

                   all       1434      14888      0.933      0.696      0.793      0.655

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    107/200      6.91G     0.8827     0.6772      1.087         58        640: 100%|██████████| 138/138 [01:13<00:00,  1.88it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.35it/s]

                   all       1434      14888      0.943      0.692      0.794      0.655

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    108/200      6.91G     0.8833     0.6772      1.081         48        640: 100%|██████████| 138/138 [01:14<00:00,  1.86it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.34it/s]

                   all       1434      14888      0.934      0.694      0.793      0.653

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    109/200      6.91G     0.8856     0.6777      1.085         22        640: 100%|██████████| 138/138 [01:14<00:00,  1.86it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.32it/s]

                   all       1434      14888      0.935      0.695      0.793      0.654

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    110/200      6.91G     0.8942     0.6906      1.089         72        640: 100%|██████████| 138/138 [01:13<00:00,  1.88it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.33it/s]

                   all       1434      14888      0.941      0.693      0.794      0.655

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    111/200      6.91G     0.8758       0.68      1.078         26        640: 100%|██████████| 138/138 [01:12<00:00,  1.89it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.31it/s]

                   all       1434      14888      0.938      0.696      0.794      0.655

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    112/200      6.91G     0.8988      0.691       1.09         29        640: 100%|██████████| 138/138 [01:13<00:00,  1.89it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.33it/s]

                   all       1434      14888      0.932        0.7      0.795      0.656

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    113/200      6.91G     0.8876     0.6809      1.082         30        640: 100%|██████████| 138/138 [01:12<00:00,  1.89it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.31it/s]

                   all       1434      14888      0.936      0.698      0.795      0.657

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    114/200      6.91G     0.8754     0.6808      1.076         47        640: 100%|██████████| 138/138 [01:12<00:00,  1.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.33it/s]

                   all       1434      14888       0.94      0.697      0.797      0.658

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    115/200      6.91G     0.8695     0.6703      1.078         43        640: 100%|██████████| 138/138 [01:12<00:00,  1.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.32it/s]

                   all       1434      14888      0.941      0.694      0.796      0.658

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    116/200      6.91G     0.8775     0.6755      1.082         79        640: 100%|██████████| 138/138 [01:12<00:00,  1.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.32it/s]

                   all       1434      14888      0.944      0.693      0.795      0.657

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    117/200      6.91G     0.8835     0.6761      1.078         46        640: 100%|██████████| 138/138 [01:12<00:00,  1.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.37it/s]

                   all       1434      14888      0.942      0.694      0.796      0.658

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    118/200      6.91G     0.8687     0.6695      1.069         73        640: 100%|██████████| 138/138 [01:12<00:00,  1.89it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:18<00:00,  2.37it/s]

                   all       1434      14888      0.939      0.695      0.796      0.658

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    119/200      6.91G     0.8651     0.6731      1.071         42        640: 100%|██████████| 138/138 [01:13<00:00,  1.87it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.32it/s]

                   all       1434      14888       0.94      0.694      0.796      0.657

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    120/200      6.91G     0.8752     0.6761      1.082         57        640: 100%|██████████| 138/138 [01:13<00:00,  1.87it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.33it/s]

                   all       1434      14888      0.936      0.698      0.795      0.659

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    121/200      6.91G     0.8841     0.6807      1.073         58        640: 100%|██████████| 138/138 [01:13<00:00,  1.88it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.33it/s]

                   all       1434      14888      0.941      0.697      0.796      0.661

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    122/200      6.91G     0.8766     0.6712      1.073         59        640: 100%|██████████| 138/138 [01:12<00:00,  1.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.34it/s]

                   all       1434      14888      0.938      0.697      0.796      0.662

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    123/200      6.91G     0.8598     0.6538      1.066         27        640: 100%|██████████| 138/138 [01:12<00:00,  1.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.33it/s]

                   all       1434      14888      0.941      0.698      0.797      0.662

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    124/200      6.91G     0.8596     0.6613      1.073         32        640: 100%|██████████| 138/138 [01:12<00:00,  1.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.32it/s]

                   all       1434      14888      0.943      0.698      0.797      0.663

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    125/200      6.91G      0.865     0.6677      1.074         30        640: 100%|██████████| 138/138 [01:12<00:00,  1.91it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.35it/s]

                   all       1434      14888      0.946      0.696      0.797      0.663

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    126/200      6.91G     0.8678     0.6665      1.071         38        640: 100%|██████████| 138/138 [01:12<00:00,  1.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.32it/s]

                   all       1434      14888      0.945      0.696      0.795      0.662

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    127/200      6.91G     0.8598     0.6649      1.073         51        640: 100%|██████████| 138/138 [01:12<00:00,  1.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.33it/s]

                   all       1434      14888      0.938      0.699      0.796      0.664

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    128/200      6.91G     0.8691     0.6684       1.07         49        640: 100%|██████████| 138/138 [01:12<00:00,  1.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.33it/s]

                   all       1434      14888       0.95      0.696      0.796      0.663

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    129/200      6.91G     0.8571     0.6602      1.068         20        640: 100%|██████████| 138/138 [01:11<00:00,  1.92it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:18<00:00,  2.37it/s]

                   all       1434      14888      0.946      0.698      0.798      0.665

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    130/200      6.91G     0.8596     0.6645      1.072         40        640: 100%|██████████| 138/138 [01:12<00:00,  1.89it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.33it/s]

                   all       1434      14888      0.943        0.7      0.798      0.666

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    131/200      6.91G     0.8591     0.6617      1.062         41        640: 100%|██████████| 138/138 [01:13<00:00,  1.88it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.31it/s]

                   all       1434      14888      0.946      0.698      0.797      0.665

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    132/200      6.91G     0.8662     0.6688      1.072         39        640: 100%|██████████| 138/138 [01:13<00:00,  1.88it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.31it/s]

                   all       1434      14888      0.946      0.698      0.798      0.666

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    133/200      6.91G     0.8665     0.6582      1.068         36        640: 100%|██████████| 138/138 [01:12<00:00,  1.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.32it/s]

                   all       1434      14888      0.944      0.699      0.798      0.666

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    134/200      6.91G     0.8554     0.6618      1.068         55        640: 100%|██████████| 138/138 [01:12<00:00,  1.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.33it/s]

                   all       1434      14888      0.949      0.695      0.797      0.665

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    135/200      6.91G     0.8397     0.6509      1.056         40        640: 100%|██████████| 138/138 [01:12<00:00,  1.91it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.29it/s]

                   all       1434      14888      0.949      0.695      0.798      0.667

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    136/200      6.91G     0.8539     0.6567      1.065         44        640: 100%|██████████| 138/138 [01:12<00:00,  1.91it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.33it/s]

                   all       1434      14888      0.937      0.701      0.797      0.667

  0%|          | 0/138 [00:00<?, ?it/s]

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    137/200      6.91G     0.8568     0.6514      1.065         46        640: 100%|██████████| 138/138 [01:12<00:00,  1.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.33it/s]

                   all       1434      14888      0.943      0.697      0.798      0.667

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    138/200      6.91G     0.8486      0.652      1.067         38        640: 100%|██████████| 138/138 [01:12<00:00,  1.91it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.34it/s]

                   all       1434      14888      0.936      0.702      0.799      0.669

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    139/200      6.91G      0.854     0.6589      1.069         39        640: 100%|██████████| 138/138 [01:12<00:00,  1.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.34it/s]

                   all       1434      14888      0.938        0.7      0.799      0.669

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    140/200      6.91G     0.8463     0.6483       1.06         31        640: 100%|██████████| 138/138 [01:11<00:00,  1.92it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:18<00:00,  2.38it/s]

                   all       1434      14888      0.939      0.701        0.8       0.67

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    141/200      6.91G     0.8507     0.6503      1.063         83        640: 100%|██████████| 138/138 [01:12<00:00,  1.89it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.34it/s]

                   all       1434      14888      0.943      0.699      0.799       0.67

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    142/200      6.91G     0.8396     0.6462      1.063         71        640: 100%|██████████| 138/138 [01:13<00:00,  1.87it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.32it/s]

                   all       1434      14888      0.939        0.7      0.799      0.669

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    143/200      6.91G      0.835      0.648      1.057         60        640: 100%|██████████| 138/138 [01:13<00:00,  1.89it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.33it/s]

                   all       1434      14888      0.945      0.699        0.8       0.67

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    144/200      6.91G     0.8447     0.6543      1.061         40        640: 100%|██████████| 138/138 [01:12<00:00,  1.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.32it/s]

                   all       1434      14888      0.941      0.701      0.799      0.671

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    145/200      6.91G     0.8532     0.6563      1.062         64        640: 100%|██████████| 138/138 [01:12<00:00,  1.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.33it/s]

                   all       1434      14888      0.941      0.703        0.8      0.672

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    146/200      6.91G     0.8366     0.6426      1.058         86        640: 100%|██████████| 138/138 [01:12<00:00,  1.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.33it/s]

                   all       1434      14888      0.944      0.702        0.8      0.672

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    147/200      6.91G     0.8345     0.6388      1.061         36        640: 100%|██████████| 138/138 [01:12<00:00,  1.89it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.34it/s]

                   all       1434      14888      0.944      0.702        0.8      0.673

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    148/200      6.91G      0.839     0.6459       1.06         53        640: 100%|██████████| 138/138 [01:12<00:00,  1.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.34it/s]

                   all       1434      14888      0.943      0.702        0.8      0.673

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    149/200      6.91G     0.8282     0.6309      1.052         34        640: 100%|██████████| 138/138 [01:12<00:00,  1.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.33it/s]

                   all       1434      14888      0.943      0.702        0.8      0.673

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    150/200      6.91G     0.8388     0.6397      1.058         68        640: 100%|██████████| 138/138 [01:12<00:00,  1.91it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.33it/s]

                   all       1434      14888      0.944      0.701      0.801      0.673

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    151/200      6.91G     0.8474      0.653      1.057         37        640: 100%|██████████| 138/138 [01:11<00:00,  1.93it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:18<00:00,  2.38it/s]

                   all       1434      14888      0.945      0.701        0.8      0.673

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    152/200      6.91G     0.8458     0.6506      1.055         42        640: 100%|██████████| 138/138 [01:12<00:00,  1.91it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:18<00:00,  2.39it/s]

                   all       1434      14888      0.943      0.702        0.8      0.673

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    153/200      6.91G     0.8195     0.6322       1.05         46        640: 100%|██████████| 138/138 [01:12<00:00,  1.89it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.34it/s]

                   all       1434      14888      0.942      0.702        0.8      0.673

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    154/200      6.91G     0.8296     0.6444       1.05         45        640: 100%|██████████| 138/138 [01:14<00:00,  1.86it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.33it/s]

                   all       1434      14888      0.944      0.702      0.801      0.674

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    155/200      6.91G     0.8305     0.6373      1.055         51        640: 100%|██████████| 138/138 [01:13<00:00,  1.88it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.34it/s]

                   all       1434      14888      0.942      0.702        0.8      0.674

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    156/200      6.91G     0.8338     0.6422       1.05         28        640: 100%|██████████| 138/138 [01:12<00:00,  1.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.35it/s]

                   all       1434      14888      0.939      0.704      0.801      0.675

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    157/200      6.91G     0.8416     0.6437      1.059         78        640: 100%|██████████| 138/138 [01:12<00:00,  1.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.34it/s]

                   all       1434      14888      0.939      0.704      0.801      0.675

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    158/200      6.91G     0.8409     0.6494      1.062         53        640: 100%|██████████| 138/138 [01:12<00:00,  1.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.34it/s]

                   all       1434      14888       0.94      0.702        0.8      0.674

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    159/200      6.91G     0.8385     0.6477      1.061         31        640: 100%|██████████| 138/138 [01:12<00:00,  1.91it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.34it/s]

                   all       1434      14888      0.941      0.702        0.8      0.674

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    160/200      6.91G     0.8397     0.6445      1.055         49        640: 100%|██████████| 138/138 [01:13<00:00,  1.89it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.29it/s]

                   all       1434      14888       0.94      0.702        0.8      0.674

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    161/200      6.91G     0.8272     0.6414      1.052         56        640: 100%|██████████| 138/138 [01:13<00:00,  1.89it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.28it/s]

                   all       1434      14888      0.938      0.703        0.8      0.674

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    162/200      6.91G     0.8283     0.6398      1.054         45        640: 100%|██████████| 138/138 [01:12<00:00,  1.89it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.30it/s]

                   all       1434      14888       0.94      0.701        0.8      0.674

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    163/200      6.91G     0.8237     0.6292      1.049         45        640: 100%|██████████| 138/138 [01:12<00:00,  1.91it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.35it/s]

                   all       1434      14888      0.936      0.704        0.8      0.675

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    164/200      6.91G     0.8244     0.6408      1.054         41        640: 100%|██████████| 138/138 [01:12<00:00,  1.89it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.31it/s]

                   all       1434      14888      0.942      0.703      0.801      0.675

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    165/200      6.91G     0.8331     0.6392       1.05         25        640: 100%|██████████| 138/138 [01:13<00:00,  1.87it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.31it/s]

                   all       1434      14888      0.946      0.701        0.8      0.675

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    166/200      6.91G     0.8321     0.6338      1.049         69        640: 100%|██████████| 138/138 [01:13<00:00,  1.88it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.31it/s]

                   all       1434      14888      0.947        0.7      0.801      0.675

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    167/200      6.91G      0.826     0.6363      1.051         40        640: 100%|██████████| 138/138 [01:13<00:00,  1.88it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.32it/s]

                   all       1434      14888      0.945      0.702      0.801      0.676

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    168/200      6.91G     0.8324     0.6372      1.048         29        640: 100%|██████████| 138/138 [01:13<00:00,  1.89it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.33it/s]

                   all       1434      14888      0.944      0.702      0.801      0.676

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    169/200      6.91G     0.8239     0.6333      1.048         66        640: 100%|██████████| 138/138 [01:12<00:00,  1.89it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.32it/s]

                   all       1434      14888      0.946      0.701      0.801      0.676

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    170/200      6.91G     0.8214     0.6335       1.05         30        640: 100%|██████████| 138/138 [01:12<00:00,  1.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.33it/s]

                   all       1434      14888      0.944      0.703      0.801      0.676

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    171/200      6.91G     0.8212     0.6309       1.05         84        640: 100%|██████████| 138/138 [01:12<00:00,  1.89it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.33it/s]

                   all       1434      14888      0.944      0.703      0.801      0.677

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    172/200      6.91G     0.8221     0.6368      1.048         37        640: 100%|██████████| 138/138 [01:12<00:00,  1.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.28it/s]

                   all       1434      14888      0.942      0.704      0.801      0.676

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    173/200      6.91G     0.8341     0.6469      1.055         49        640: 100%|██████████| 138/138 [01:12<00:00,  1.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.31it/s]

                   all       1434      14888      0.943      0.703      0.801      0.676

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    174/200      6.91G     0.8172     0.6284      1.043         45        640: 100%|██████████| 138/138 [01:12<00:00,  1.91it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.35it/s]

                   all       1434      14888      0.944      0.703      0.801      0.677

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    175/200      6.91G     0.8173     0.6359      1.047         54        640: 100%|██████████| 138/138 [01:12<00:00,  1.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.36it/s]

                   all       1434      14888      0.945      0.703      0.802      0.677

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    176/200      6.91G      0.822     0.6348      1.053         38        640: 100%|██████████| 138/138 [01:13<00:00,  1.89it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.37it/s]

                   all       1434      14888      0.942      0.703      0.802      0.676

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    177/200      6.91G      0.821     0.6349      1.055         31        640: 100%|██████████| 138/138 [01:14<00:00,  1.86it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.34it/s]

                   all       1434      14888      0.941      0.704      0.802      0.677

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    178/200      6.91G     0.8157      0.635      1.047         60        640: 100%|██████████| 138/138 [01:13<00:00,  1.87it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.33it/s]

                   all       1434      14888      0.941      0.705      0.802      0.677

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    179/200      6.91G     0.8113     0.6241      1.046         59        640: 100%|██████████| 138/138 [01:13<00:00,  1.87it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.34it/s]

                   all       1434      14888      0.941      0.705      0.802      0.677

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    180/200      6.91G     0.8184       0.63      1.049         53        640: 100%|██████████| 138/138 [01:12<00:00,  1.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.34it/s]

                   all       1434      14888      0.941      0.705      0.802      0.677

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    181/200      6.91G     0.8363     0.6459      1.053         47        640: 100%|██████████| 138/138 [01:12<00:00,  1.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.32it/s]

                   all       1434      14888      0.941      0.704      0.801      0.677

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    182/200      6.91G     0.8154     0.6259       1.05         32        640: 100%|██████████| 138/138 [01:13<00:00,  1.89it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.32it/s]

                   all       1434      14888      0.942      0.704      0.802      0.678

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    183/200      6.91G     0.8116     0.6187      1.045         47        640: 100%|██████████| 138/138 [01:12<00:00,  1.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.32it/s]

                   all       1434      14888      0.943      0.704      0.802      0.678

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    184/200      6.91G     0.8192     0.6319      1.049         63        640: 100%|██████████| 138/138 [01:12<00:00,  1.91it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.31it/s]

                   all       1434      14888      0.942      0.703      0.801      0.677

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    185/200      6.91G     0.8149     0.6315      1.051         36        640: 100%|██████████| 138/138 [01:12<00:00,  1.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.35it/s]

                   all       1434      14888      0.942      0.704      0.801      0.677

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    186/200      6.91G     0.8137     0.6271       1.05         74        640: 100%|██████████| 138/138 [01:12<00:00,  1.91it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:18<00:00,  2.38it/s]

                   all       1434      14888      0.942      0.703      0.801      0.677

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    187/200      6.91G     0.8114     0.6341      1.051         65        640: 100%|██████████| 138/138 [01:11<00:00,  1.92it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:18<00:00,  2.39it/s]

                   all       1434      14888      0.942      0.704      0.801      0.677

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    188/200      6.91G     0.8185      0.634      1.049         56        640: 100%|██████████| 138/138 [01:12<00:00,  1.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:18<00:00,  2.39it/s]

                   all       1434      14888      0.942      0.704      0.802      0.677

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    189/200      6.91G     0.8063     0.6196      1.044         38        640: 100%|██████████| 138/138 [01:13<00:00,  1.88it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:18<00:00,  2.39it/s]

                   all       1434      14888      0.942      0.703      0.801      0.677

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    190/200      6.91G     0.8136     0.6255       1.05         46        640: 100%|██████████| 138/138 [01:13<00:00,  1.89it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:18<00:00,  2.40it/s]

                   all       1434      14888      0.942      0.703      0.802      0.677
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, num_output_channels=3, method='weighted_average'), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    191/200      6.91G     0.7236      0.524      1.002         30        640: 100%|██████████| 138/138 [01:13<00:00,  1.88it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:18<00:00,  2.40it/s]

                   all       1434      14888      0.942      0.704      0.802      0.677

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    192/200      6.91G     0.7241     0.5238      1.005         30        640: 100%|██████████| 138/138 [01:12<00:00,  1.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:18<00:00,  2.41it/s]

                   all       1434      14888      0.942      0.703      0.802      0.677

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    193/200      6.91G     0.7241     0.5295      1.007         37        640: 100%|██████████| 138/138 [01:13<00:00,  1.88it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:18<00:00,  2.37it/s]

                   all       1434      14888      0.942      0.704      0.802      0.677

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    194/200      6.91G     0.7352     0.5304      1.005         40        640: 100%|██████████| 138/138 [01:13<00:00,  1.88it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.36it/s]

                   all       1434      14888      0.942      0.704      0.801      0.677

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    195/200      6.91G     0.7306     0.5331      1.013         29        640: 100%|██████████| 138/138 [01:13<00:00,  1.89it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.36it/s]

                   all       1434      14888      0.941      0.704      0.801      0.676

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    196/200      6.91G      0.727     0.5264      1.007         28        640: 100%|██████████| 138/138 [01:13<00:00,  1.89it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.34it/s]

                   all       1434      14888      0.941      0.703      0.801      0.676

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    197/200      6.91G     0.7271     0.5274      1.006         42        640: 100%|██████████| 138/138 [01:12<00:00,  1.91it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.34it/s]

                   all       1434      14888      0.941      0.704      0.801      0.676

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    198/200      6.91G     0.7239      0.529      1.008         49        640: 100%|██████████| 138/138 [01:11<00:00,  1.92it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.34it/s]

                   all       1434      14888      0.942      0.704      0.801      0.676

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    199/200      6.91G      0.725      0.526      1.007         38        640: 100%|██████████| 138/138 [01:11<00:00,  1.92it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.35it/s]

                   all       1434      14888      0.941      0.703      0.801      0.676

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    200/200      6.91G     0.7228     0.5257      1.005         45        640: 100%|██████████| 138/138 [01:12<00:00,  1.91it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:19<00:00,  2.33it/s]

                   all       1434      14888      0.942      0.704      0.802      0.676

200 epochs completed in 5.149 hours.
Optimizer stripped from runs/detect/mbvfss_finetune/weights/last.pt, 19.0MB
Optimizer stripped from runs/detect/mbvfss_finetune/weights/best.pt, 19.0MB

Validating runs/detect/mbvfss_finetune/weights/best.pt...
Ultralytics 8.3.161 🚀 Python-3.11.11 torch-2.6.0+cu124 CUDA:0 (Tesla T4, 15095MiB)
                                                        CUDA:1 (Tesla T4, 15095MiB)
YOLOv12s summary (fused): 159 layers, 9,236,298 parameters, 0 gradients, 21.2 GFLOPs

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:20<00:00,  2.15it/s]
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all       1434      14888      0.943      0.704      0.801      0.677
    Aortic enlargement       1000       2282      0.992       0.59      0.765      0.681
           Atelectasis         85        128      0.965      0.859      0.906       0.79
         Calcification        192        443      0.895      0.617      0.749       0.56
          Cardiomegaly        745       1725      0.994      0.562      0.733      0.664
         Consolidation        170        288      0.926      0.784      0.855      0.774
                   ILD        161        419       0.98      0.809      0.868      0.799
          Infiltration        263        564      0.955      0.787      0.852      0.755
          Lung Opacity        559       1210      0.956      0.769      0.859      0.737
           Nodule/Mass        344       1368      0.868      0.541      0.647      0.465
          Other lesion        445        989      0.945      0.783      0.865      0.714
      Pleural effusion        460       1155      0.922      0.687      0.814      0.648
    Pleural thickening        782       2165      0.925      0.743      0.851      0.644
          Pneumothorax         38         87      0.946      0.621      0.658      0.611
    Pulmonary fibrosis        657       2065      0.928      0.701      0.797      0.637
Speed: 0.2ms preprocess, 8.5ms inference, 0.0ms loss, 2.4ms postprocess per image
Results saved to runs/detect/mbvfss_finetune

🎯 Final validation:
Ultralytics 8.3.161 🚀 Python-3.11.11 torch-2.6.0+cu124 CUDA:0 (Tesla T4, 15095MiB)
                                                        CUDA:1 (Tesla T4, 15095MiB)
YOLOv12s summary (fused): 159 layers, 9,236,298 parameters, 0 gradients, 21.2 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 2290.3±386.1 MB/s, size: 136.7 KB)

val: Scanning /kaggle/working/vinbigdata/labels/val.cache... 1434 images, 0 backgrounds, 0 corrupt: 100%|██████████| 1434/1434 [00:00<?, ?it/s]

WARNING ⚠️ cache='ram' may produce non-deterministic training results. Consider cache='disk' as a deterministic alternative if your disk space allows.

val: Caching images (1.6GB RAM): 100%|██████████| 1434/1434 [00:03<00:00, 438.37it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 45/45 [00:32<00:00,  1.39it/s]
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all       1434      14888      0.943      0.703      0.801      0.678
    Aortic enlargement       1000       2282      0.991       0.59      0.763      0.681
           Atelectasis         85        128      0.967      0.859      0.906      0.789
         Calcification        192        443      0.895      0.615       0.75      0.562
          Cardiomegaly        745       1725      0.994      0.561      0.734      0.665
         Consolidation        170        288      0.926      0.784      0.855      0.771
                   ILD        161        419       0.98      0.808      0.868        0.8
          Infiltration        263        564      0.955      0.788      0.852      0.757
          Lung Opacity        559       1210      0.958      0.768      0.859      0.738
           Nodule/Mass        344       1368      0.868       0.54      0.645      0.465
          Other lesion        445        989      0.945      0.782      0.866      0.716
      Pleural effusion        460       1155      0.923      0.686      0.815      0.651
    Pleural thickening        782       2165      0.927      0.742      0.848      0.644
          Pneumothorax         38         87      0.946      0.621      0.658      0.612
    Pulmonary fibrosis        657       2065      0.928        0.7      0.797      0.638
Speed: 0.2ms preprocess, 16.2ms inference, 0.0ms loss, 1.3ms postprocess per image
Results saved to runs/detect/mbvfss_finetune2

In [17]:
test_df = pd.read_csv(f'/kaggle/input/vinbigdata-{size}-image-dataset/vinbigdata/test.csv')

In [18]:
test_dir = f'/kaggle/input/vinbigdata-{size}-image-dataset/vinbigdata/test'
os.listdir('/kaggle/working/runs/detect/train/weights/')

FileNotFoundError: [Errno 2] No such file or directory: '/kaggle/working/runs/detect/train/weights/'

In [ ]:
weights_dir = "/kaggle/working/runs/detect/train/weights/best.pt"  # Trọng số mô hình đã huấn luyện

model = YOLO(weights_dir)

results = model.predict(
    source=test_dir,
    imgsz=640,
    conf=0.005,
    iou=0.45,
    save_txt=True,
    save_conf=True,
    project="/kaggle/working/runs/detect",  
    name="exp",                            
    exist_ok=True,                         
    save=True,
    verbose=False# Lưu ảnh với bounding box
)

In [ ]:
import os
import matplotlib.pyplot as plt
from PIL import Image

# 1. Point to your YOLO output directory
output_dir = "/kaggle/working/runs/detect/exp"

# 2. Gather all .jpg/.png files
images = [
    os.path.join(output_dir, f)
    for f in sorted(os.listdir(output_dir))
    if f.lower().endswith((".jpg", ".png"))
]

# 3. Display the first 4 results in a 2×2 grid
plt.figure(figsize=(12, 12))
for i, img_path in enumerate(images[:4]):
    img = Image.open(img_path)
    plt.subplot(2, 2, i + 1)
    plt.imshow(img)
    plt.axis("off")
plt.tight_layout()
plt.show()

In [ ]:
# ─── Cell: Validation-Batch Visualization ───
# Author: mo

import os
import re
from typing import List, Tuple, Optional
from PIL import Image
import matplotlib.pyplot as plt

def get_val_batch_pairs(dir_path: str) -> List[Tuple[str, str]]:
    label_regex = re.compile(r"val_batch(\d+)_labels\.\w+$")
    pred_regex  = re.compile(r"val_batch(\d+)_pred\.\w+$")
    labels, preds = {}, {}

    for root, _, files in os.walk(dir_path):
        for fname in files:
            full = os.path.join(root, fname)
            m = label_regex.match(fname)
            if m:
                labels[int(m.group(1))] = full
            m = pred_regex.match(fname)
            if m:
                preds[int(m.group(1))] = full

    idxs = sorted(set(labels) & set(preds))
    if not idxs:
        raise ValueError(f"No pairs found in {dir_path}")
    return [(labels[i], preds[i]) for i in idxs]

def show_val_batch_comparisons(
    dir_path: str,
    max_batches: Optional[int] = None,
    save_path: Optional[str] = None
) -> None:
    pairs = get_val_batch_pairs(dir_path)
    if max_batches is not None:
        pairs = pairs[:max_batches]
    n = len(pairs)
    fig, axs = plt.subplots(n, 2, figsize=(12, 4*n), squeeze=False)

    for i, (lab, pred) in enumerate(pairs):
        for j, (path, title) in enumerate([(lab, "Labels"), (pred, "Predictions")]):
            axs[i][j].imshow(Image.open(path))
            axs[i][j].set_title(f"Batch {i}: {title}")
            axs[i][j].axis("off")

    plt.tight_layout()
    if save_path:
        plt.savefig(save_path, bbox_inches="tight")
        print(f"Saved to {save_path}")
    plt.show()

# ─── End of Cell ───────────────────────────

In [ ]:
# Show up to the first 6 validation batches:
show_val_batch_comparisons(
    dir_path="/kaggle/working/runs/detect/train",
    max_batches=6
)

In [ ]:
# ─── Cell: Validation-Batch Visualization (Enlarged) ───
# Author: mo

import os
import re
from typing import List, Tuple, Optional
from PIL import Image
import matplotlib.pyplot as plt

def get_val_batch_pairs(dir_path: str) -> List[Tuple[str, str]]:
    label_regex = re.compile(r"val_batch(\d+)_labels\.\w+$")
    pred_regex  = re.compile(r"val_batch(\d+)_pred\.\w+$")
    labels, preds = {}, {}

    for root, _, files in os.walk(dir_path):
        for fname in files:
            full = os.path.join(root, fname)
            m = label_regex.match(fname)
            if m:
                labels[int(m.group(1))] = full
            m = pred_regex.match(fname)
            if m:
                preds[int(m.group(1))] = full

    idxs = sorted(set(labels) & set(preds))
    if not idxs:
        raise ValueError(f"No pairs found in {dir_path}")
    return [(labels[i], preds[i]) for i in idxs]

def show_val_batch_comparisons(
    dir_path: str,
    max_batches: Optional[int] = None,
    save_path: Optional[str] = None,
    dpi: int = 150,
    width_per_image: float = 8.0,
    height_per_image: float = 6.0
) -> None:
    """
    Display enlarged validation batch label vs. prediction comparisons.

    Args:
        dir_path (str): Directory containing validation batch images.
        max_batches (Optional[int]): Limit display to first N batches.
        save_path (Optional[str]): Filepath to save the figure (optional).
        dpi (int): Dots-per-inch of the resulting figure.
        width_per_image (float): Width in inches of each subplot.
        height_per_image (float): Height in inches of each subplot.
    """
    pairs = get_val_batch_pairs(dir_path)
    if max_batches is not None:
        pairs = pairs[:max_batches]
    n = len(pairs)
    if n == 0:
        raise ValueError("No batches to display after filtering.")

    # Compute total figure size
    fig_width  = width_per_image * 2       # two columns
    fig_height = height_per_image * n      # one row per batch

    fig, axs = plt.subplots(
        nrows=n,
        ncols=2,
        figsize=(fig_width, fig_height),
        squeeze=False,
        dpi=dpi
    )

    for i, (lab, pred) in enumerate(pairs):
        for j, (path, title) in enumerate([(lab, "Labels"), (pred, "Predictions")]):
            axs[i][j].imshow(Image.open(path))
            axs[i][j].set_title(f"Batch {i}: {title}", fontsize=16)
            axs[i][j].axis("off")

    plt.tight_layout()
    if save_path:
        plt.savefig(save_path, bbox_inches="tight")
        print(f"Saved comparison figure to: {save_path}")
    plt.show()

# ─── End of Cell ───────────────────────────

In [ ]:
show_val_batch_comparisons(
    dir_path="runs/detect/train",
    max_batches=6,          # for example
    dpi=200,                # even sharper
    width_per_image=10.0,   # wider
    height_per_image=7.5    # taller
)